[build]
  base = "."
  command = "npm install && npm install vite --save-dev && npx vite build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "ws", "uuid"]
  included_files = ["server/**/*"]

[functions."api"]
  external_node_modules = ["express", "ws", "uuid"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
